cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/Cypress
    - node_modules
    - dist

## Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

install:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: .pre
  script:
    - touch ~/.npmrc
    - echo $GITHUB_PKG_REGISTRY >> ~/.npmrc
    - echo $GITHUB_PKG_TOKEN >> ~/.npmrc
    - yarn install --frozen-lockfile
    - yarn build

linter:
  image: node:16-alpine
  stage: .pre
  script:
    - yarn lint

unit:
  image: node:16-alpine
  stage: .pre
  script:
    - yarn test

typescript:
  image: node:16-alpine
  stage: .pre
  script:
    - yarn typescript

.build:
  image: node:16-alpine
  stage: build
  script:
    - yarn build
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - dist

cypress test:
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  stage: test
  script:
    - yarn preview &
    - yarn cypress run --record --key 295871b0-fbab-4338-abd8-9320895a84f0 --browser chrome --group "UI - Chrome"
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
