version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env.dev
    environment:
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ./.env.dev
    ports:
      - $PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=db
      - DB_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$DATABASE_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  db: